export interface Post {
  id: number;
  author: string;
  handle: string;
  avatarInitials: string;
  avatarColor: string;
  time: string;
  stadtteil: string;
  content: string;
  comments: number;
  reposts: number;
  likes: number;
  category: string;
  verified?: boolean;
  hashtags?: string[];
}

export const feedPosts: Post[] = [
  {
    id: 1,
    author: "Stadt Bielefeld",
    handle: "@stadt_bielefeld",
    avatarInitials: "ST",
    avatarColor: "bg-blue-600",
    time: "8 Min.",
    stadtteil: "Mitte",
    content: "🚧 Achtung Anwohner:innen der Detmolder Straße: Ab Montag startet die zweite Bauphase. Alle Infos zur Umleitung findet ihr im Verkehrs-Kanal. Bitte plant mehr Zeit ein!",
    comments: 21,
    reposts: 38,
    likes: 142,
    category: "Verkehr",
    verified: true,
    hashtags: ["#Bielefeld", "#Baustelle"],
  },
  {
    id: 20,
    author: "Sven B.",
    handle: "@svenbielefeldkommt",
    avatarInitials: "SB",
    avatarColor: "bg-sky-500",
    time: "14 Min.",
    stadtteil: "Mitte",
    content: "Bielefeld Wetter heute: ☀️ 5 Minuten → 🌧️ 2 Stunden → ☀️ 3 Minuten → ⛈️ ohne Ankündigung → ☀️ kurz bevor alle schlafen gehen. Jedes. Mal. 😂",
    comments: 67,
    reposts: 143,
    likes: 512,
    category: "Humor",
    hashtags: ["#Bielefeld", "#WetterBielefeld"],
  },
  {
    id: 2,
    author: "Lena aus Schildesche",
    handle: "@lena_bi",
    avatarInitials: "LE",
    avatarColor: "bg-purple-500",
    time: "29 Min.",
    stadtteil: "Schildesche",
    content: "Heute Abend Open-Air-Kino im Bürgerpark! Jemand Lust mitzukommen? 🎬🌿 Eintritt frei, Decke mitbringen. Wir freuen uns auf einen lauen Sommerabend!",
    comments: 18,
    reposts: 12,
    likes: 87,
    category: "Veranstaltung",
    hashtags: ["#Schildesche", "#SommerInBielefeld"],
  },
  {
    id: 21,
    author: "BielefelderMemes",
    handle: "@bi_memes",
    avatarInitials: "BM",
    avatarColor: "bg-yellow-500",
    time: "45 Min.",
    stadtteil: "Mitte",
    content: "POV: Du erklaerst Leuten aus anderen Staedten wo Bielefeld liegt.\n\n\"Zwischen Hannover und Dortmund.\"\n\"Kenn ich nicht.\"\n\"An der A2.\"\n\"Ah nein.\"\n\"Sparrenburg?\"\n\"Nie gehoert.\"\n\nBielefeld existiert. Wir sind nur gut versteckt \u{1F62D}\u{1F3F0}",
    comments: 89,
    reposts: 201,
    likes: 834,
    category: "Humor",
    hashtags: ["#BielefeldExistiert", "#Bielefeld"],
  },
  {
    id: 3,
    author: "Bielefelder Wochenmarkt",
    handle: "@wochenmarkt_bi",
    avatarInitials: "WM",
    avatarColor: "bg-orange-500",
    time: "1 Std.",
    stadtteil: "Altstadt",
    content: "Frische Erdbeeren aus der Region sind da! 🍓 Schaut am Samstag am Klosterplatz vorbei — wir freuen uns auf euch. Auch Biolebensmittel, frisches Brot und regionale Käsesorten gibt es wieder.",
    comments: 9,
    reposts: 54,
    likes: 213,
    category: "Markt",
    verified: true,
    hashtags: ["#Wochenmarkt", "#Regional"],
  },
  {
    id: 22,
    author: "Priya K.",
    handle: "@priya_bi",
    avatarInitials: "PK",
    avatarColor: "bg-fuchsia-500",
    time: "1 Std.",
    stadtteil: "Brackwede",
    content: "Wer kennt das: Bus kommt zu spät → ich laufe zur nächsten Haltestelle → der Bus überholt mich dabei. 😭\n\nErnst gemeinte Frage: Wird der ÖPNV in Bielefeld besser oder schlechter? Ich bemerke in letzter Zeit mehr Ausfälle als früher.",
    comments: 54,
    reposts: 78,
    likes: 291,
    category: "Diskussion",
    hashtags: ["#ÖPNV", "#Bielefeld", "#Stadtverkehr"],
  },
  {
    id: 4,
    author: "Markus K.",
    handle: "@markus_brackwede",
    avatarInitials: "MK",
    avatarColor: "bg-teal-500",
    time: "2 Std.",
    stadtteil: "Brackwede",
    content: "Der Gehweg an der Hauptstraße (Höhe Sparkasse) ist seit Wochen kaputt. Ich habe mehrere Male bei der Stadt angerufen — keine Reaktion. Wer hat ähnliche Erfahrungen gemacht? Zusammen machen wir das sichtbar! 💪",
    comments: 34,
    reposts: 67,
    likes: 189,
    category: "Anliegen",
    hashtags: ["#Brackwede", "#GehwegMelden"],
  },
  {
    id: 23,
    author: "Leon S.",
    handle: "@leon_ravensberger",
    avatarInitials: "LS",
    avatarColor: "bg-lime-600",
    time: "2 Std.",
    stadtteil: "Mitte",
    content: "Spontane Grillparty heute Abend am Ravensberger Park! ☀️🍖\n\nGrill & Kohle ist dabei, bringt einfach was zu essen oder trinken mit. Ab 18 Uhr, beim großen Baum am Teich.\n\nJe mehr, desto besser — einfach vorbeikommen! 🎉",
    comments: 41,
    reposts: 62,
    likes: 237,
    category: "Community",
    hashtags: ["#Bielefeld", "#Grillen", "#RavensbergerPark"],
  },
  {
    id: 5,
    author: "DSC Arminia Bielefeld",
    handle: "@arminia_bsc",
    avatarInitials: "AR",
    avatarColor: "bg-blue-800",
    time: "3 Std.",
    stadtteil: "Mitte",
    content: "🔵⚪ Heimspiel am Samstag! Wir brauchen eure Unterstützung auf der Alm. Tickets noch verfügbar — kommt zahlreich! Gemeinsam ist Bielefeld unschlagbar. ⚽",
    comments: 67,
    reposts: 132,
    likes: 421,
    category: "Sport",
    verified: true,
    hashtags: ["#DSCArminia", "#Bielefeld"],
  },
  {
    id: 24,
    author: "Julia M.",
    handle: "@julia_mitte",
    avatarInitials: "JM",
    avatarColor: "bg-red-400",
    time: "3 Std.",
    stadtteil: "Mitte",
    content: "Heißeste Meinung des Tages 🔥\n\nDer beste Döner in Bielefeld ist NICHT am Hauptbahnhof.\n\nEs gibt mindestens 3 Läden in der Innenstadt die haushoch gewinnen. Gebt mir eure Empfehlungen — ich teste sie alle durch 🌯👇",
    comments: 112,
    reposts: 87,
    likes: 398,
    category: "Diskussion",
    hashtags: ["#Bielefeld", "#Döner", "#LocalFood"],
  },
  {
    id: 6,
    author: "Grüne Bielefeld",
    handle: "@gruene_bi",
    avatarInitials: "GR",
    avatarColor: "bg-green-600",
    time: "4 Std.",
    stadtteil: "Gadderbaum",
    content: "📊 Abstimmungsergebnis: 78 % der Befragten wünschen sich mehr Fahrradwege in Brackwede. Der Stadtrat berät nächste Woche darüber. Eure Stimmen haben Gewicht — danke fürs Mitmachen!",
    comments: 45,
    reposts: 89,
    likes: 312,
    category: "Politik",
    verified: true,
    hashtags: ["#Fahrrad", "#Verkehrswende"],
  },
  {
    id: 25,
    author: "Max F.",
    handle: "@max_jahnplatz",
    avatarInitials: "MF",
    avatarColor: "bg-slate-500",
    time: "4 Std.",
    stadtteil: "Mitte",
    content: "📢 Fundsache!\n\nIch habe heute am Jahnplatz (gegen 14 Uhr) einen schwarzen Nike-Rucksack gefunden. Drin: ein Schlüsselbund und ein Notizbuch.\n\nWenn er dir gehört, schreib mir bitte eine DM mit Beschreibung! Ich bring ihn dann vorbei 🙏",
    comments: 23,
    reposts: 91,
    likes: 156,
    category: "Community",
    hashtags: ["#Bielefeld", "#Fundsache"],
  },
  {
    id: 7,
    author: "Aysun T.",
    handle: "@aysun_bi",
    avatarInitials: "AY",
    avatarColor: "bg-rose-500",
    time: "5 Std.",
    stadtteil: "Stieghorst",
    content: "Der Spielplatz am Stieghorster Park macht mir Sorgen. Mehrere Geräte sind gesperrt, Schaukeln kaputt. Unsere Kinder spielen dort täglich. Wann wird endlich etwas repariert?",
    comments: 28,
    reposts: 43,
    likes: 156,
    category: "Anliegen",
    hashtags: ["#Stieghorst", "#Spielplatz"],
  },
  {
    id: 26,
    author: "Uni Bielefeld",
    handle: "@uni_bielefeld",
    avatarInitials: "UB",
    avatarColor: "bg-indigo-600",
    time: "6 Std.",
    stadtteil: "Schildesche",
    content: "Erinnerung: Die Mensa schließt heute bereits um 13:30 Uhr wegen Betriebsversammlung.\n\nAlternativplan: Pommes vom Imbiss gegenüber. Wie immer. 🍟😂\n\nEin schönes Wochenende euch allen!",
    comments: 44,
    reposts: 66,
    likes: 287,
    category: "Humor",
    verified: true,
    hashtags: ["#UniBielefeld", "#Mensa", "#Studentenleben"],
  },
  {
    id: 8,
    author: "Café Kiepenkerl",
    handle: "@kiepenkerl_bi",
    avatarInitials: "CK",
    avatarColor: "bg-amber-600",
    time: "7 Std.",
    stadtteil: "Mitte",
    content: "☕ Sonntags-Brunch ab 10 Uhr! Hausgemachte Waffeln, Rührei vom Biobauern und frisch gepresste Säfte. Kommt vorbei — Reservierungen unter 0521/123456. Wir freuen uns auf euch!",
    comments: 14,
    reposts: 28,
    likes: 98,
    category: "Gastronomie",
    hashtags: ["#Brunch", "#Bielefeld"],
  },
  {
    id: 9,
    author: "Jöllenbecker Nachbarschaft",
    handle: "@joellenbeck_bi",
    avatarInitials: "JN",
    avatarColor: "bg-indigo-500",
    time: "8 Std.",
    stadtteil: "Jöllenbeck",
    content: "📢 Bürgerversammlung zu den geplanten Radwegen in Jöllenbeck: Dienstag, 1. Juli, 19 Uhr im Gemeindehaus. Alle Anwohner:innen sind herzlich eingeladen! Bringt eure Fragen mit.",
    comments: 31,
    reposts: 58,
    likes: 174,
    category: "Politik",
    hashtags: ["#Jöllenbeck", "#RadwegJöllenbeck"],
  },
  {
    id: 27,
    author: "Fatima A.",
    handle: "@fatima_sennestadt",
    avatarInitials: "FA",
    avatarColor: "bg-violet-500",
    time: "9 Std.",
    stadtteil: "Sennestadt",
    content: "Ich weiß nicht ob das nur mir so geht, aber Bielefeld hat sich in den letzten 2 Jahren SO positiv verändert. Mehr Grün, nettere Leute, bessere Cafés.\n\nOder bilde ich mir das nur ein weil Frühling ist? 🌸 Was denkt ihr?",
    comments: 78,
    reposts: 55,
    likes: 342,
    category: "Diskussion",
    hashtags: ["#Bielefeld", "#Heimatliebe"],
  },
  {
    id: 10,
    author: "Nina S.",
    handle: "@nina_sennestadt",
    avatarInitials: "NS",
    avatarColor: "bg-pink-500",
    time: "10 Std.",
    stadtteil: "Sennestadt",
    content: "Heute hat mir ein unbekannter Passant geholfen, meinen Einkauf nach Hause zu tragen, weil ich auf Krücken war 🥹 So schön, wenn man merkt: Bielefeld ist eine Stadt mit Herz. Danke, lieber Mensch!",
    comments: 52,
    reposts: 71,
    likes: 348,
    category: "Community",
    hashtags: ["#Sennestadt", "#Bielefeld"],
  },
  {
    id: 28,
    author: "Sparrenburg Fan Club",
    handle: "@sparrenburg_bi",
    avatarInitials: "SF",
    avatarColor: "bg-stone-600",
    time: "11 Std.",
    stadtteil: "Mitte",
    content: "Heute Nacht um 0:03 Uhr wird die Sparrenburg 700 Jahre alt 🏰✨\n\nFakt: Sie hat mehr Touristen überlebt als jeder andere Bielefelder Bürger jemals Ausländern erklären konnte wo Bielefeld ist.\n\nAlles Gute, alte Dame! 🥂",
    comments: 91,
    reposts: 178,
    likes: 621,
    category: "Humor",
    hashtags: ["#Sparrenburg", "#Bielefeld700"],
  },
  {
    id: 11,
    author: "Stadtwerke Bielefeld",
    handle: "@stadtwerke_bi",
    avatarInitials: "SW",
    avatarColor: "bg-cyan-600",
    time: "Gestern",
    stadtteil: "Mitte",
    content: "⚡ Geplante Wartungsarbeiten am Stromnetz in Teilen von Brackwede: Donnerstag 8–13 Uhr. Betroffene Straßen findet ihr auf unserer Website. Wir bitten um Entschuldigung für die Unannehmlichkeiten.",
    comments: 8,
    reposts: 22,
    likes: 47,
    category: "Infrastruktur",
    verified: true,
    hashtags: ["#Stadtwerke", "#Brackwede"],
  },
  {
    id: 13,
    author: "Musikschule Bielefeld",
    handle: "@musikschule_bi",
    avatarInitials: "MB",
    avatarColor: "bg-violet-500",
    time: "Gestern",
    stadtteil: "Mitte",
    content: "🎵 Sommerkonzert unserer Schüler:innen: 28. Juni, 17 Uhr, Ravensberger Park. Eintritt frei! Von Klassik bis Jazz — alle Altersklassen spielen. Kommt und unterstützt die jungen Talente Bielefelds!",
    comments: 23,
    reposts: 45,
    likes: 201,
    category: "Kultur",
    verified: true,
    hashtags: ["#Musik", "#Bielefeld"],
  },
  {
    id: 14,
    author: "Kemal Y.",
    handle: "@kemal_brackwede",
    avatarInitials: "KY",
    avatarColor: "bg-emerald-500",
    time: "Gestern",
    stadtteil: "Brackwede",
    content: "Unser Nachbarschaftsgarten in Brackwede braucht Unterstützung! Wir suchen Freiwillige für Samstag (10–14 Uhr). Bringt Gartenhandschuhe mit, Kaffee gibt es von uns. Gemeinsam machen wir das Grün schöner! 🌱",
    comments: 16,
    reposts: 29,
    likes: 122,
    category: "Community",
    hashtags: ["#Brackwede", "#Nachbarschaft", "#Garten"],
  },
];

export const trendingTopics = [
  { tag: "#BielefeldExistiert", count: "4.201 Beiträge" },
  { tag: "#Sparrenburg700", count: "2.341 Beiträge" },
  { tag: "#Stadtfest2026", count: "1.872 Beiträge" },
  { tag: "#RadwegJöllenbeck", count: "984 Beiträge" },
  { tag: "#DSCArminia", count: "5.124 Beiträge" },
];

export const upcomingEvents = [
  { name: "Leinewebermarkt", date: "12.–15. Juli", location: "Innenstadt" },
  { name: "Carnival der Kulturen", date: "29. Juni", location: "Kesselbrink" },
  { name: "Nacht der Klänge", date: "6. Juli", location: "Sparrenburg" },
  { name: "Bielefelder Bürgerfest", date: "20. Juli", location: "Alter Markt" },
];

export const stadtteile = [
  "Mitte", "Schildesche", "Brackwede", "Stieghorst",
  "Gadderbaum", "Jöllenbeck", "Sennestadt", "Altstadt",
];
