export interface Post {
  id: number;
  author: string;
  handle: string;
  avatarInitials: string;
  avatarColor: string;
  time: string;
  stadtteil: string;
  content: string;
  comments: number;
  reposts: number;
  likes: number;
  category: string;
  verified?: boolean;
  image?: string;
  hashtags?: string[];
}

export const feedPosts: Post[] = [
  {
    id: 1,
    author: "Stadt Bielefeld",
    handle: "@stadt_bielefeld",
    avatarInitials: "ST",
    avatarColor: "bg-blue-600",
    time: "12 Min.",
    stadtteil: "Mitte",
    content: "🚧 Achtung Anwohner:innen der Detmolder Straße: Ab Montag startet die zweite Bauphase. Alle Infos zur Umleitung findet ihr im Verkehrs-Kanal. Bitte plant mehr Zeit ein!",
    comments: 21,
    reposts: 38,
    likes: 142,
    category: "Verkehr",
    verified: true,
    hashtags: ["#Bielefeld", "#Baustelle"],
  },
  {
    id: 2,
    author: "Lena aus Schildesche",
    handle: "@lena_bi",
    avatarInitials: "LE",
    avatarColor: "bg-purple-500",
    time: "32 Min.",
    stadtteil: "Schildesche",
    content: "Heute Abend Open-Air-Kino im Bürgerpark! Jemand Lust mitzukommen? 🎬🌿 Eintritt frei, Decke mitbringen. Wir freuen uns auf einen lauen Sommerabend!",
    comments: 18,
    reposts: 12,
    likes: 87,
    category: "Veranstaltung",
    hashtags: ["#Schildesche", "#SommerInBielefeld"],
  },
  {
    id: 3,
    author: "Bielefelder Wochenmarkt",
    handle: "@wochenmarkt_bi",
    avatarInitials: "WM",
    avatarColor: "bg-orange-500",
    time: "1 Std.",
    stadtteil: "Altstadt",
    content: "Frische Erdbeeren aus der Region sind da! 🍓 Schaut am Samstag am Klosterplatz vorbei — wir freuen uns auf euch. Auch Biolebensmittel, frisches Brot und regionale Käsesorten gibt es wieder.",
    comments: 9,
    reposts: 54,
    likes: 213,
    category: "Markt",
    verified: true,
    hashtags: ["#Wochenmarkt", "#Regional"],
  },
  {
    id: 4,
    author: "Markus K.",
    handle: "@markus_brackwede",
    avatarInitials: "MK",
    avatarColor: "bg-teal-500",
    time: "2 Std.",
    stadtteil: "Brackwede",
    content: "Der Gehweg an der Hauptstraße (Höhe Sparkasse) ist seit Wochen kaputt. Ich habe mehrere Male bei der Stadt angerufen — keine Reaktion. Wer hat ähnliche Erfahrungen gemacht? Zusammen machen wir das sichtbar! 💪",
    comments: 34,
    reposts: 67,
    likes: 189,
    category: "Anliegen",
    hashtags: ["#Brackwede", "#GehwegMelden"],
  },
  {
    id: 5,
    author: "DSC Arminia Bielefeld",
    handle: "@arminia_bsc",
    avatarInitials: "AR",
    avatarColor: "bg-blue-800",
    time: "3 Std.",
    stadtteil: "Mitte",
    content: "🔵⚪ Heimspiel am Samstag! Wir brauchen eure Unterstützung auf der Alm. Tickets noch verfügbar — kommt zahlreich! Gemeinsam ist Bielefeld unschlagbar. ⚽",
    comments: 67,
    reposts: 132,
    likes: 421,
    category: "Sport",
    verified: true,
    hashtags: ["#DSCArminia", "#Bielefeld"],
  },
  {
    id: 6,
    author: "Grüne Bielefeld",
    handle: "@gruene_bi",
    avatarInitials: "GR",
    avatarColor: "bg-green-600",
    time: "4 Std.",
    stadtteil: "Gadderbaum",
    content: "📊 Abstimmungsergebnis: 78 % der Befragten wünschen sich mehr Fahrradwege in Brackwede. Der Stadtrat berät nächste Woche darüber. Eure Stimmen haben Gewicht — danke fürs Mitmachen!",
    comments: 45,
    reposts: 89,
    likes: 312,
    category: "Politik",
    verified: true,
    hashtags: ["#Fahrrad", "#Verkehrswende"],
  },
  {
    id: 7,
    author: "Aysun T.",
    handle: "@aysun_bi",
    avatarInitials: "AY",
    avatarColor: "bg-rose-500",
    time: "5 Std.",
    stadtteil: "Stieghorst",
    content: "Der Spielplatz am Stieghorster Park macht mir Sorgen. Mehrere Geräte sind gesperrt, Schaukeln kaputt. Unsere Kinder spielen dort täglich. Wann wird endlich etwas repariert?",
    comments: 28,
    reposts: 43,
    likes: 156,
    category: "Anliegen",
    hashtags: ["#Stieghorst", "#Spielplatz"],
  },
  {
    id: 8,
    author: "Café Kiepenkerl",
    handle: "@kiepenkerl_bi",
    avatarInitials: "CK",
    avatarColor: "bg-amber-600",
    time: "6 Std.",
    stadtteil: "Mitte",
    content: "☕ Sonntags-Brunch ab 10 Uhr! Hausgemachte Waffeln, Rührei vom Biobauern und frisch gepresste Säfte. Kommt vorbei — Reservierungen unter 0521/123456. Wir freuen uns auf euch!",
    comments: 14,
    reposts: 28,
    likes: 98,
    category: "Gastronomie",
    verified: false,
    hashtags: ["#Brunch", "#Bielefeld"],
  },
  {
    id: 9,
    author: "Jöllenbecker Nachbarschaft",
    handle: "@joellenbeck_bi",
    avatarInitials: "JN",
    avatarColor: "bg-indigo-500",
    time: "7 Std.",
    stadtteil: "Jöllenbeck",
    content: "📢 Bürgerversammlung zu den geplanten Radwegen in Jöllenbeck: Dienstag, 1. Juli, 19 Uhr im Gemeindehaus. Alle Anwohner:innen sind herzlich eingeladen! Bringt eure Fragen mit.",
    comments: 31,
    reposts: 58,
    likes: 174,
    category: "Politik",
    hashtags: ["#Jöllenbeck", "#RadwegJöllenbeck"],
  },
  {
    id: 10,
    author: "Nina S.",
    handle: "@nina_sennestadt",
    avatarInitials: "NS",
    avatarColor: "bg-pink-500",
    time: "8 Std.",
    stadtteil: "Sennestadt",
    content: "Heute hat mir ein unbekannter Passant geholfen, meinen Einkauf nach Hause zu tragen, weil ich auf Krücken war 🥹 So schön, wenn man merkt: Bielefeld ist eine Stadt mit Herz. Danke, lieber Mensch!",
    comments: 52,
    reposts: 71,
    likes: 348,
    category: "Community",
    hashtags: ["#Sennestadt", "#Bielefeld"],
  },
  {
    id: 11,
    author: "Stadtwerke Bielefeld",
    handle: "@stadtwerke_bi",
    avatarInitials: "SW",
    avatarColor: "bg-cyan-600",
    time: "9 Std.",
    stadtteil: "Mitte",
    content: "⚡ Geplante Wartungsarbeiten am Stromnetz in Teilen von Brackwede: Donnerstag 8–13 Uhr. Betroffene Straßen findet ihr auf unserer Website. Wir bitten um Entschuldigung für die Unannehmlichkeiten.",
    comments: 8,
    reposts: 22,
    likes: 47,
    category: "Infrastruktur",
    verified: true,
    hashtags: ["#Stadtwerke", "#Brackwede"],
  },
  {
    id: 12,
    author: "Thomas R.",
    handle: "@thomas_bibi",
    avatarInitials: "TR",
    avatarColor: "bg-slate-500",
    time: "10 Std.",
    stadtteil: "Schildesche",
    content: "Hat jemand Infos zum neuen Bauprojekt an der Heeperstraße? Dort stehen jetzt Bauschilder, aber keine Erklärung was gebaut wird. Wäre schön wenn die Stadt kommunizieren würde was da geplant ist 🤔",
    comments: 19,
    reposts: 14,
    likes: 83,
    category: "Stadtentwicklung",
    hashtags: ["#Schildesche", "#Stadtentwicklung"],
  },
  {
    id: 13,
    author: "Musikschule Bielefeld",
    handle: "@musikschule_bi",
    avatarInitials: "MB",
    avatarColor: "bg-violet-500",
    time: "Gestern",
    stadtteil: "Mitte",
    content: "🎵 Sommerkonzert unserer Schüler:innen: 28. Juni, 17 Uhr, Ravensberger Park. Eintritt frei! Von Klassik bis Jazz — alle Altersklassen spielen. Kommt und unterstützt die jungen Talente Bielefelds!",
    comments: 23,
    reposts: 45,
    likes: 201,
    category: "Kultur",
    verified: true,
    hashtags: ["#Musik", "#Bielefeld"],
  },
  {
    id: 14,
    author: "Kemal Y.",
    handle: "@kemal_brackwede",
    avatarInitials: "KY",
    avatarColor: "bg-emerald-500",
    time: "Gestern",
    stadtteil: "Brackwede",
    content: "Unser Nachbarschaftsgarten in Brackwede braucht Unterstützung! Wir suchen Freiwillige für Samstag (10–14 Uhr). Bringt Gartenhandschuhe mit, Kaffee gibt es von uns. Gemeinsam machen wir das Grün schöner! 🌱",
    comments: 16,
    reposts: 29,
    likes: 122,
    category: "Community",
    hashtags: ["#Brackwede", "#Nachbarschaft", "#Garten"],
  },
  {
    id: 15,
    author: "Bielefeld Spricht",
    handle: "@bielefeld_spricht",
    avatarInitials: "BS",
    avatarColor: "bg-green-700",
    time: "Gestern",
    stadtteil: "Mitte",
    content: "📣 Neue Funktion: Jetzt könnt ihr direkt über aktuelle Stadtthemen abstimmen! Geht zur Abstimmungs-Seite und macht eure Stimme zu Themen wie Fahrradwegen, Parks und Verkehr hörbar. Demokratie beginnt nebenan. 🗳️",
    comments: 44,
    reposts: 96,
    likes: 387,
    category: "Plattform",
    verified: true,
    hashtags: ["#BielefeldSpricht", "#Demokratie"],
  },
];

export const trendingTopics = [
  { tag: "#Sparrenburg", count: "2.341 Beiträge" },
  { tag: "#Stadtfest2026", count: "1.872 Beiträge" },
  { tag: "#RadwegJöllenbeck", count: "984 Beiträge" },
  { tag: "#TeutoburgerWald", count: "612 Beiträge" },
  { tag: "#DSCArminia", count: "5.124 Beiträge" },
];

export const upcomingEvents = [
  { name: "Leinewebermarkt", date: "12.–15. Juli", location: "Innenstadt" },
  { name: "Carnival der Kulturen", date: "29. Juni", location: "Kesselbrink" },
  { name: "Nacht der Klänge", date: "6. Juli", location: "Sparrenburg" },
  { name: "Bielefelder Bürgerfest", date: "20. Juli", location: "Alter Markt" },
];

export const stadtteile = [
  "Mitte", "Schildesche", "Brackwede", "Stieghorst",
  "Gadderbaum", "Jöllenbeck", "Sennestadt", "Altstadt",
];
